[api] Expose express server metrics for prometheus
LuatixHQ/opencti pull request #1598
Opened 2021-09-27 14:37 UTC by debelyoo

### Proposed changes

* Expose metrics for prometheus
* Use express-prometheus-middleware

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/1595

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

Exposing the metrics can be enabled by adding the following env variables to the container:

- `APP__EXPOSE_METRICS=true`

2021-10-10 12:06 UTC, richard-julien requested changes

2021-10-10 12:06 UTC, richard-julien commented on opencti-platform/opencti-graphql/config/default.json
> +    "expose_metrics": false,
I think metrics is not only prometheus. We need to prepare the possibility to have more metrics providers exposed (lie https://github.com/open-telemetry/opentelemetry-js)

I think about a little more conplex configuration like

```
"telemetry": {
    "prometheus": {
        "enabled": false,
        "metrics_path": "/metrics"
    }
}
```

telemetry should be disable by default to prevent performance impact

2021-10-10 12:06 UTC, richard-julien commented on opencti-platform/opencti-graphql/src/http/httpPlatform.js
> +  const exposeMetrics = booleanConf('app:expose_metrics', false);
Change it to use the right configuration

2021-10-10 12:06 UTC, richard-julien commented on opencti-platform/opencti-graphql/src/http/httpPlatform.js
> +        metricsPath: '/metrics',
Change it to use the right configuration.
Need also to be tested if its working well with basePath configured

2021-10-11 08:42 UTC, debelyoo commented on opencti-platform/opencti-graphql/config/default.json
> +    "expose_metrics": false,
Yes, makes sense 👍

2021-10-11 10:17 UTC, debelyoo commented on opencti-platform/opencti-graphql/src/http/httpPlatform.js
> +        metricsPath: '/metrics',
The `base_path` config property is not used by the prometheus middleware. The full path of the metrics endpoint has to be defined in the `metricsPath` property.

2021-10-11 21:27 UTC, richard-julien commented on opencti-platform/opencti-graphql/src/http/httpPlatform.js
> +        metricsPath: '/metrics',
I think you have to concatenate yourself the basePath like we do for other middleware.  You can take a look at apolloServer.applyMiddleware

2021-10-13 06:06 UTC, debelyoo commented on opencti-platform/opencti-graphql/src/http/httpPlatform.js
> +        metricsPath: '/metrics',
Ok. I updated the code.

2021-10-13 21:52 UTC, richard-julien commented on opencti-platform/opencti-graphql/src/http/httpPlatform.js
> +        metricsPath: '/metrics',
Have you updated the PR?

2021-10-14 05:53 UTC, debelyoo commented on opencti-platform/opencti-graphql/src/http/httpPlatform.js
> +        metricsPath: '/metrics',
Oups I forgot. Sorry for that.

2021-10-15 20:57 UTC, merged