Switch object storage to use AWS S3 SDK
LuatixHQ/opencti pull request #2260
Opened 2022-07-30 16:34 UTC by jake-walker

### Proposed changes

The MinIO SDK has been switched out for the official S3 SDK which brings benefits when using EC2 instance profiles (as implemented in #2168) as well as working better with S3 (the correct regional endpoints are used for the region that the bucket is in).

### Related issues

* Although already resolved, this provides a better fix for #2024

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### Further comments

As explained briefly above, using the AWS S3 SDK adds a number of benefits while still being completely compatible with MinIO. It should also work better with other 'S3 compatible' storages like GCP Cloud Storage, Azure Blob Storage, etc... as the AWS SDK is the 'standard'.

The original functions in `opencti-platform/opencti-graphql/src/database/minio.js` have been kept but completely rewritten with the new SDK using only async code (whereas before it was a bit of a mixture between async and promises) which makes the code much cleaner.

The fetching of credentials as implemented in #2168 is improved by using the AWS SDK. Now a custom ['credential provider'](https://aws.amazon.com/blogs/developer/credential-providers-credential-management-part-3/) which pulls credentials first from the regular configuration file or environment variables, then falls back to using an attached AWS IAM role if available. The AWS SDK does a better job at automatically checking when credentials expire so the hacky code to check for that (from the previous PR) has now been removed. The configuration option for using the AWS role has been removed too, as it can automatically fall back if no configuration is set.

I would have changed the configuration section from 'minio' to 'object-storage' or 's3' but it could involve breaking changes. I think having backwards compatibily (i.e. load first from the 'object-storage' section, then if not use the 'minio' section) over complicates the code too much which is why I have just left it as 'minio'. I think this could be worth discussing because the standard for storage is S3, not MinIO anymore.

2022-07-30 17:34 UTC, ReadyElbow commented
One note: the 'use_aws_role' environment variable should be removed from the Notion documentation. 

https://luatix.notion.site/Configuration-a568604c46d84f39a8beae141505572a#:~:text=Accept%20all-,minio%3Ause_aws_role,-Show%20All

2022-07-31 10:08 UTC, jake-walker commented
> One note: the `use_aws_role` environment variable should be removed from the Notion documentation.
> 
> https://luatix.notion.site/Configuration-a568604c46d84f39a8beae141505572a#:~:text=Accept%20all-,minio%3Ause_aws_role,-Show%20All

As 'ChangeMe' could be used in some environments as well as the CI pipeline, I have re-added the variable from before which now skips loading the credentials from the configuration file and would use the AWS role instead.

2022-08-03 23:02 UTC, richard-julien requested changes
Review and test still in progress

2022-08-03 23:02 UTC, richard-julien commented on opencti-platform/opencti-graphql/src/database/file-storage.js
> +}
In case of multiple files this code will fail because items will be transformed as a promise.

Code proposal to replace.

return Promise.all(objects
        .filter((o) => !isFileObjectExcluded(o.Key))
        .map((item) => loadFile(user, item.Key)));

2022-08-03 23:02 UTC, richard-julien commented on opencti-platform/opencti-graphql/src/database/file-storage.js
> +  const key = joinPaths(path, filename);
I start some testing and looks like the upload is no longer working with minio
The file is no more created inside a hierarchy of directory
To be replace with

> const key = \`${path}/${filename}`;

2022-08-04 09:58 UTC, richard-julien commented on opencti-platform/opencti-graphql/tests/02-integration/01-database/object-storage-test.js
> +describe('Object storage file listing', () => {
File must be renamed to file-storage-test.js

2022-08-04 12:37 UTC, jake-walker commented on opencti-platform/opencti-graphql/src/database/file-storage.js
> +  const key = joinPaths(path, filename);
I wasn't able to reproduce the problem on my end, but your suggestion should functionally be the same.

2022-08-04 14:18 UTC, richard-julien approved these changes

2022-08-04 14:19 UTC, merged