[backend/frontend] Added support for Consent Message on Login Page
LuatixHQ/opencti pull request #3274
Opened 2023-05-03 16:23 UTC by ParamConstructor

### Proposed changes

This PR allows for a customizable (off settings GUI by Admin) "Consent to Monitor" or "Legal Notice" message ('platform_consent_message') that is displayed beneath the 'platform_login_message' (if configured) on the Login Page. If the new ('platform_consent_message') is configured, the message will be displayed on the login page, and the user will be required to click a consent check box agreeing to the displayed terms, before the Login Form is displayed.

If the new ('platform_consent_message') is blank in the configuration, the login page will ignore this field and display nothing.

### Related issues

This PR has been tested with LDAP configuration and standard internal OpenCTI authentication. If a customer has configured some sort of SSO authentication that bypasses the login page, then the message will not be displayed. The submitter does not have this type of configuration to test against, so implementation of an intermediate popup/module screen based on SSO configuration would be an additional PR to supplement this work.

### Checklist

- [ X ] I consider the submitted work as finished
- [ X ] I tested the code for its functionality
- [ X ] I wrote test cases for the relevant uses case
-          Tested manually within the GUI. A future PR will have Selenium autotest to supplement this capability automatically.
- [ ] I added/update the relevant documentation (either on github or on notion)
-          This has not been done, suspect the ('platform_consent_message')  option needs to be added to Notion page documentation.
- [ X ] Where necessary I refactored code to improve the overall quality

### Further comments

None.

2023-05-25 14:37 UTC, Kedae requested changes

2023-05-25 14:37 UTC, Kedae commented on opencti-platform/opencti-front/src/private/components/settings/Settings.js
> +                              {t('Platform Consent Message')}
You are missing some Localization translation in the files.

Additionnaly, in this screen we do not have such "h1" title, maybe you can remove it ?

2023-05-25 14:37 UTC, Kedae commented on opencti-platform/opencti-front/src/private/components/settings/Settings.js
> +                              fullWidth={true}
You don't need to add ={true} in React component, it's redundant. I know we have done it **a lot** in the code, but you can remove it from this part :)

2023-05-25 14:37 UTC, Kedae commented on opencti-platform/opencti-front/src/public/components/Login.tsx
> +  const isConsentMessage = consentMessage && consentMessage.length > 0;
I think you can use the isEmptyField utils we already have for this.

2023-05-25 14:37 UTC, Kedae commented on opencti-platform/opencti-front/src/public/components/Login.tsx
> +      {consentMessage && consentMessage.length > 0 && (
You should use the constant previously created

2023-05-25 14:37 UTC, Kedae commented on opencti-platform/opencti-front/src/public/components/Login.tsx
> +          <Markdown> I have read and comply with the above statement: </Markdown>
Why you add this message hardcoded way and you do not set it as a default value in the message ?

2023-05-25 14:37 UTC, Kedae commented on opencti-platform/opencti-front/src/public/components/Login.tsx
> +import Checkbox from '@mui/material/Checkbox';
Linter error here

2023-05-25 14:37 UTC, Kedae commented on opencti-platform/opencti-front/src/public/components/Login.tsx
> +          <Checkbox name='consent' edge='start' onChange={handleChange} style={{ margin: 0 }}></Checkbox>
Could you try to align this checkbox with the line of text of compliance ?

2023-05-25 14:46 UTC, ParamConstructor commented on opencti-platform/opencti-front/src/private/components/settings/Settings.js
> +                              {t('Platform Consent Message')}
Translation Request here is to add to the various translations for the text of "Platform Consent Message" and others that are wrapped with t() into opencti-platform/opencti-front/src/utils/Localization.js?

2023-05-25 14:47 UTC, ParamConstructor commented on opencti-platform/opencti-front/src/public/components/Login.tsx
> +      {consentMessage && consentMessage.length > 0 && (
@Kedae - replace with isConsentMessage constant - sorry about that....

2023-05-25 14:48 UTC, Kedae commented on opencti-platform/opencti-front/src/private/components/settings/Settings.js
> +                              {t('Platform Consent Message')}
Yes exactly. We use i18n to translate the app and the Localization.js file contains all the translation. So you need to add all the new keys within t() inside this file for every language. Basically we use Google to translate the text (and obviously we will be able to help you on the French one :) )

2023-05-25 14:48 UTC, ParamConstructor commented on opencti-platform/opencti-front/src/public/components/Login.tsx
> +          <Markdown> I have read and comply with the above statement: </Markdown>
@Kedae - will correct and make part of opencti-platform/opencti-front/src/utils/Localization.js as a string.

2023-05-25 16:41 UTC, ParamConstructor commented on opencti-platform/opencti-front/src/public/components/Login.tsx
> +          <Checkbox name='consent' edge='start' onChange={handleChange} style={{ margin: 0 }}></Checkbox>
@Kedae Placed in Box tags and aligned as requested.

2023-05-25 16:42 UTC, ParamConstructor commented on opencti-platform/opencti-front/src/public/components/Login.tsx
> +import Checkbox from '@mui/material/Checkbox';
@Kedae check-ts and lint have been run to fix any errant issues. Should be resolved on current commit.

2023-05-25 16:44 UTC, ParamConstructor commented on opencti-platform/opencti-front/src/public/components/Login.tsx
> +          <Markdown> I have read and comply with the above statement: </Markdown>
@Kedae A new graphql field has been added (platform_consent_confirm_text). This is by default, if left blank on the Setting page, set to "I have read and comply with the above statement". Translations have been added for the default string. An Admin can set a new message in the Setting page to replace this default message/string.

Is this agreeable?

2023-05-25 16:45 UTC, ParamConstructor commented on opencti-platform/opencti-front/src/public/components/Login.tsx
> +      {consentMessage && consentMessage.length > 0 && (
@Kedae - Fixed to use constant (isConsentMessage).

2023-05-25 16:46 UTC, ParamConstructor commented on opencti-platform/opencti-front/src/private/components/settings/Settings.js
> +                              fullWidth={true}
@Kedae - Fixed to just read 'fullWidth' versus 'fullWidth={true}'

2023-05-25 17:49 UTC, ParamConstructor commented on opencti-platform/opencti-front/src/private/components/settings/Settings.js
> +                              {t('Platform Consent Message')}
@Kedae - I believe this is all of them that are required. Added translations for:      
- 'Platform Consent Message'
- 'Platform Consent Message - requires acceptance to enable login form when set'
- 'I have read and comply with the above statement'
- 'Platform Consent Confirm Text - confirm label next to confirm checkbox'

2023-05-25 17:49 UTC, ParamConstructor commented on opencti-platform/opencti-front/src/private/components/settings/Settings.js
> +                              {t('Platform Consent Message')}
@Kedae - I believe this is all of them that are required. Added translations for:      
- 'Platform Consent Message'
- 'Platform Consent Message - requires acceptance to enable login form when set'
- 'I have read and comply with the above statement'
- 'Platform Consent Confirm Text - confirm label next to confirm checkbox'

2023-05-25 18:14 UTC, ParamConstructor commented on opencti-platform/opencti-front/src/public/components/Login.tsx
> +  const isConsentMessage = consentMessage && consentMessage.length > 0;
@Kedae - Fixed with isNotEmptyField() from utils.

2023-06-01 09:08 UTC, richard-julien commented
Hi @ParamConstructor,

Some remarks on the PR.

- The confirm button doesn't hide all the SSO buttons for now, i think sso should also be hidden until validation
- UI configuration is now a bit unbalance between left side and right side, we need to rework a bit the screen. There is also some problem in change detection some times, that is not related to your work but maybe could be interesting to also take care here.
- Do you think it could be possible for you to activate https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork ? Could be very interesting to be able for us to also directly commit on your branch for this kind of remarks that will be quicker to just fix :)

2023-06-01 13:57 UTC, ParamConstructor commented
@richard-julien - The "Allow edits by maintainers" feature apparently only works if the forked repo is not part of an organization :-(. They have an open bug on this - https://github.com/orgs/community/discussions/5634 I tried to enable it - but the checkbox is not even displayed on my PRs to enable (as referenced in the open issue). In this PR, we had not wrapped the SSO method to have to consent - but I can make that update.

The "unbalanced" setting screen will correct itself when you accept/merge the PR for the header/footer stuff. (#3302 ). The Header/Footer configuration options are in the left side where the unbalance exists - making the setting screen back to "even" distribution of configuration options.

2023-06-01 17:43 UTC, ParamConstructor commented
@richard-julien @Kedae - SSO SAML has been tested. Support for SSO and removing from the login page before consent has been accepted has been added to the PR. PR has been rebased to master, as of the time of this comment.

2023-06-10 14:46 UTC, merged