[frontend] Fix double click on add/update opinion in entities
LuatixHQ/opencti pull request #4062
Opened 2023-08-11 08:25 UTC by RomuDeuxfois

### Need help

* I try to fix this issues for the second time. I am not able to reproduce in local, so it's complicated to find the fix. If someone have some ideas to help me on it, I would appreciate.

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/3838

2023-08-11 08:58 UTC, yassine-ouaamou commented
I will try to reproduce

2023-08-13 20:02 UTC, Kedae requested changes

2023-08-13 20:02 UTC, Kedae commented on opencti-platform/opencti-front/src/private/components/analyses/opinions/StixCoreObjectOpinionsRadar.tsx
>          onCompleted: () => {
updater: () => fetchQuery(),
        onCompleted: () => {
          setSubmitting(false);
          resetForm();
        },

2023-08-13 20:02 UTC, Kedae commented on opencti-platform/opencti-front/src/private/components/analyses/opinions/StixCoreObjectOpinionsRadar.tsx
>          onCompleted: () => {
updater: () => fetchQuery(),
        onCompleted: () => {
          setSubmitting(false);
          resetForm();
        },

2023-08-13 20:03 UTC, Kedae commented
Testable with slow 3G throttling.

The issue is that we fetch the query (i.e try to re-render the component) while mutating the relay store = Kaboom.
Updater function is called when the local relay store HAS been updated, not while completion.

2023-08-14 08:22 UTC, Kedae submitted a review, later dismissed

2023-08-14 09:10 UTC, yassine-ouaamou commented
I still reproduce this bug using the 3G throttling
![throttling](https://github.com/OpenCTI-Platform/opencti/assets/7083405/8e540927-a5ca-4816-a55b-335192f7c2d1)

2023-08-14 12:34 UTC, SarahBocognano commented
Tested: Still happening is Slow 3G, we first have the "create" button appearing, then when clicking, the "update" button finally appears"

2023-08-14 14:47 UTC, SouadHadjiat commented
I still have the bug too with "fast 3G" or less. The dialog keeps displaying even though the "open" variable is false. You can't close it with "Cancel" button, you need to update again or change any value. The only way I found to close the dialog is to close it at the beggining of `onSubmit`, because it looks like in `onComplete `or `updater`, we don't really have the same scope anymore, because of the refetch query.

2023-08-30 11:26 UTC, closed without merging