Issue/4178 define a default dashboard for a group or an organization
LuatixHQ/opencti pull request #4197
Opened 2023-08-30 08:06 UTC by yassine-ouaamou

### Proposed changes

* Ability de select a default dashboard for a group or an organization

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/4178

2023-08-30 13:28 UTC, Archidoit commented
Missing translations:
- Default dashboard
- tooltip content

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/865ffaa3-8a00-4e44-bc98-ea260d527e3f)

2023-08-30 13:29 UTC, Archidoit commented
behavior OK 💯

2023-08-30 14:24 UTC, RomuDeuxfois requested changes

2023-08-30 14:24 UTC, RomuDeuxfois commented on opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionOverview.tsx
> +const groupMutationRelationAdd = graphql`
It's not a good idea to add these mutations, just to satisfy useFormEditor contracts.

We need to have a useFormEditor for internal object or have a composition of hooks.
@Kedae any ideas on it ?

I saw the same problem in SettingsOrganizationEdition

2023-08-31 07:05 UTC, Kedae commented on opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionOverview.tsx
> +const groupMutationRelationAdd = graphql`
Couldn't agree more.

2023-08-31 08:43 UTC, SarahBocognano reviewed
Tested ✅ Behavior works well, as @Archidoit said, the translation is missing but the rest is okay

2023-08-31 10:04 UTC, RomuDeuxfois commented on opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionOverview.tsx
> +const groupMutationRelationAdd = graphql`
An idea

```
import { GraphQLTaggedNode } from 'relay-runtime/lib/query/RelayModernGraphQLTag';
import { useMutation } from 'react-relay';
import { ObjectSchema, SchemaObjectDescription } from 'yup';
import { Option } from '../../private/components/common/form/ReferenceField';
import {
  convertAssignees,
  convertExternalReferences,
  convertKillChainPhases,
  convertMarkings, convertParticipants,
} from '../edition';

export interface GenericData {
  id: string;
  readonly objectMarking: {
    readonly edges: ReadonlyArray<{
      readonly node: {
        readonly definition: string | null;
        readonly definition_type: string | null;
        readonly id: string;
      };
    }>;
  } | null;
  readonly objectAssignee?: {
    readonly edges: ReadonlyArray<{
      readonly node: {
        readonly entity_type: string;
        readonly id: string;
        readonly name: string;
      };
    }>;
  } | null;
  readonly killChainPhases?: {
    readonly edges: ReadonlyArray<{
      readonly node: {
        readonly id: string;
        readonly kill_chain_name: string;
        readonly phase_name: string;
        readonly x_opencti_order: number | null;
      };
    }>;
  } | null;
}

interface Queries {
  fieldPatch: GraphQLTaggedNode;
  editionFocus: GraphQLTaggedNode;
  relationAdd?: GraphQLTaggedNode;
  relationDelete?: GraphQLTaggedNode;
}

const useFormEditor = (
  data: GenericData,
  enableReferences: boolean,
  queries: Queries,
  validator: ObjectSchema<{ [p: string]: unknown }>,
) => {
  const [commitFieldPatch] = useMutation(queries.fieldPatch);
  const [commitEditionFocus] = useMutation(queries.editionFocus);
  const schemaFields = (validator.describe() as SchemaObjectDescription).fields;

  const validate = (
    name: string,
    values: number | number[] | string | Date | Option | Option[],
    callback: () => void,
  ) => {
    if (schemaFields[name]) {
      validator
        .validateAt(name, { [name]: values })
        .then(() => {
          callback();
        })
        .catch(() => false);
    } else {
      callback();
    }
  };

  // Simple
  const changeCreated = (name: string, value: Option) => {
    if (!enableReferences) {
      validate(name, value, () => {
        commitFieldPatch({
          variables: {
            id: data.id,
            input: [
              {
                key: 'createdBy',
                value: [value.value],
              },
            ],
          },
        });
      });
    }
  };
  const changeFocus = (name: string) => {
    commitEditionFocus({
      variables: {
        id: data.id,
        input: {
          focusOn: name,
        },
      },
    });
  };
  const changeField = (name: string, value: number | number[] | string | Date | Option | Option[]) => {
    if (!enableReferences) {
      let finalValue = value;
      if (name === 'x_opencti_workflow_id') {
        finalValue = (value as Option).value;
      }
      validate(name, value, () => {
        commitFieldPatch({
          variables: {
            id: data.id,
            input: [{ key: name, value: finalValue || '' }],
          },
        });
      });
    }
  };

  // Multiple
  if (queries.relationAdd && queries.relationDelete) {
    const [commitRelationAdd] = useMutation(queries.relationAdd);
    const [commitRelationDelete] = useMutation(queries.relationDelete);
    const changeMultiple = (
      name: string,
      values: Option[],
      relation: string,
      optionMapper: (data: unknown) => [Option],
    ) => {
      if (!enableReferences) {
        validate(name, values, () => {
          const currentValues: [Option] = optionMapper(data);
          const added = values.filter(
            (v) => !currentValues.map((c) => c.value).includes(v.value),
          );
          const removed = currentValues.filter(
            (c) => !values.map((v) => v.value).includes(c.value),
          );
          if (added.length > 0) {
            commitRelationAdd({
              variables: {
                id: data.id,
                input: {
                  toId: added[0].value,
                  relationship_type: relation,
                },
              },
            });
          }
          if (removed.length > 0) {
            commitRelationDelete({
              variables: {
                id: data.id,
                toId: removed[0].value,
                relationship_type: relation,
              },
            });
          }
        });
      }
    };
    const changeMarking = (name: string, values: Option[]) => {
      changeMultiple(name, values, 'object-marking', convertMarkings);
    };
    const changeAssignee = (name: string, values: Option[]) => {
      changeMultiple(name, values, 'object-assignee', convertAssignees);
    };
    const changeParticipant = (name: string, values: Option[]) => {
      changeMultiple(name, values, 'object-participant', convertParticipants);
    };
    const changeKillChainPhases = (name: string, values: Option[]) => {
      changeMultiple(name, values, 'kill-chain-phase', convertKillChainPhases);
    };
    const changeExternalReferences = (name: string, values: Option[]) => {
      changeMultiple(
        name,
        values,
        'external-reference',
        convertExternalReferences,
      );
    };
    return {
      changeMarking,
      changeAssignee,
      changeParticipant,
      changeCreated,
      changeKillChainPhases,
      changeExternalReferences,
      changeFocus,
      changeField,
      fieldPatch: commitFieldPatch,
    };
  }

  return {
    changeCreated,
    changeFocus,
    changeField,
    fieldPatch: commitFieldPatch,
  };
};

export default useFormEditor;

```

2023-08-31 22:31 UTC, merged

2023-08-31 22:32 UTC, SamuelHassine commented
@yassine-ouaamou TODO: please think about fixing comments from @RomuDeuxfois and @Kedae in another PR.