[backend/frontend] Implement full text search for documents (#1483)
LuatixHQ/opencti pull request #4275
Opened 2023-09-07 19:07 UTC by SouadHadjiat

### Proposed changes

Draft PR with first test of indexing a file
*
*

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/1483
*

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-10-11 07:20 UTC, Archidoit commented
Is it usefull to keep the 'line view' button on the right since there is no other view possibility ? 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/05360b23-d1a5-4e3a-8946-e9c1c11a57f7)

2023-10-11 07:22 UTC, RomuDeuxfois commented on opencti-platform/opencti-graphql/src/manager/fileIndexManager.ts
> +// TODO add limit for number of files ?
There are things left

2023-10-11 07:22 UTC, RomuDeuxfois commented on opencti-platform/opencti-graphql/src/manager/fileIndexManager.ts
> +  if (mimeTypes?.length > 0) {
This is not possible to have this filter direclty in the S3client ? When we send the request ?

2023-10-11 07:22 UTC, RomuDeuxfois commented on opencti-platform/opencti-graphql/src/manager/fileIndexManager.ts
> +        // test if markings or organization sharing or authorized members or authorities have been updated
I don't understand why we check on this (makring, authorities)

2023-10-11 07:22 UTC, RomuDeuxfois commented on opencti-platform/opencti-graphql/src/manager/fileIndexManager.ts
> +  const fileListingOpts = { modifiedSince: fromDate, excludePath: 'import/pending/' };
Is this part not enough to index the new files? Rather than also adding stream handler management?
All files added in an entity update end up in minio.

2023-10-11 07:22 UTC, RomuDeuxfois commented on opencti-platform/opencti-front/src/private/components/search/SearchIndexedFileLine.tsx
> +    <ListItem
Better to use ListItemButton

2023-10-11 07:22 UTC, RomuDeuxfois commented on opencti-platform/opencti-front/src/private/components/search/SearchIndexedFiles.tsx
> +        isSortable: true,
Can you use render here ?

2023-10-11 07:22 UTC, RomuDeuxfois commented on opencti-platform/opencti-front/src/private/components/search/SearchIndexedFileLine.tsx
> +          <div>
You can use render in SearchIndexedFiles.tsx to simplify this code

2023-10-11 07:22 UTC, Archidoit commented
If we click again on 'Extends this search to indexed files', it would be great that the panel closes. 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/c6fd034b-9aa9-4874-844e-65aae3a08c80)

2023-10-11 07:27 UTC, Archidoit commented
Sorting file result (by name or 'attached entity type' is not working : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/0dcc0cd2-af39-4200-a811-761b4cd014f5)

Note: Would be great to also be able to sort by the number of occurences

2023-10-11 07:32 UTC, Archidoit commented
What are all the files extensions for which this feature is working ?

2023-10-11 07:33 UTC, SouadHadjiat commented on opencti-platform/opencti-graphql/src/manager/fileIndexManager.ts
> +  if (mimeTypes?.length > 0) {
no there is no filter on mime types in listObjects query

2023-10-11 07:35 UTC, SouadHadjiat commented on opencti-platform/opencti-graphql/src/manager/fileIndexManager.ts
> +  const fileListingOpts = { modifiedSince: fromDate, excludePath: 'import/pending/' };
what do you mean ? The manager has two parts : one that indexes all new uploaded files in minio, another one that listens to the stream to update indexed files linked to entities if markings / organization restrictions changes.

2023-10-11 07:36 UTC, SouadHadjiat commented on opencti-platform/opencti-front/src/private/components/search/SearchIndexedFiles.tsx
> +        isSortable: true,
it is not sortable for now, it should be false here.

2023-10-11 07:38 UTC, SouadHadjiat commented
> What are all the files extensions for which this feature is working ?

@Archidoit We support these mime types : text/plain, text/csv, application/pdf, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet (excel sheets). you can find them in default.json

2023-10-11 07:40 UTC, SouadHadjiat commented
> Sorting file result (by name or 'attached entity type' is not working : ![image](https://user-images.githubusercontent.com/75783086/274177665-0dcc0cd2-af39-4200-a811-761b4cd014f5.png)
> 
> Note: Would be great to also be able to sort by the number of occurences

It's a mistake, we don't support custom sorting for now (it will be in V2), we forgot to remove column sorting. And sorting by number of occurrence won't be possible, because it's a data we compute, not something stored that we could sort on.

2023-10-11 07:42 UTC, SouadHadjiat commented on opencti-platform/opencti-graphql/src/manager/fileIndexManager.ts
> +        // test if markings or organization sharing or authorized members or authorities have been updated
we listen to the stream and filter events that are only updates on markings / organization restrictions.
authorized members and authorities are not handled yet, the comment should be : `// test if markings or organization sharing have been updated`

2023-10-11 08:23 UTC, RomuDeuxfois commented on opencti-platform/opencti-front/src/private/components/search/SearchIndexedFiles.tsx
> +        isSortable: true,
I mean the render property

      isSortable: true,
      render: (node: Organization) => node.name,

2023-10-11 08:23 UTC, RomuDeuxfois commented on opencti-platform/opencti-graphql/src/database/engine.js
> +export const elConfigureAttachmentProcessor = async () => {
Awesome !

2023-10-11 08:23 UTC, RomuDeuxfois commented on opencti-platform/opencti-graphql/src/database/file-storage.js
> +      messages: [],
Why this changes ?

2023-10-11 08:49 UTC, Jipegien commented
> Sorting file result (by name or 'attached entity type' is not working : ![image](https://user-images.githubusercontent.com/75783086/274177665-0dcc0cd2-af39-4200-a811-761b4cd014f5.png)
> 
> Note: Would be great to also be able to sort by the number of occurences @Jipegien

Agreed. Should be able to sort by filename, date, entity type and number of occurences.

2023-10-11 15:37 UTC, SouadHadjiat commented on opencti-platform/opencti-graphql/src/database/file-storage.js
> +      messages: [],
for typescript typing

2023-10-11 15:38 UTC, SouadHadjiat commented
> > Sorting file result (by name or 'attached entity type' is not working : ![image](https://user-images.githubusercontent.com/75783086/274177665-0dcc0cd2-af39-4200-a811-761b4cd014f5.png)
> > Note: Would be great to also be able to sort by the number of occurences @Jipegien
> 
> Agreed. Should be able to sort by filename, date, entity type and number of occurences.

@Jipegien it's not possible to sort by number of occurrence. About other sorting, we can only sort by filename, and uploadDate, not by entity_type, or entity_name. for V2

2023-10-11 15:41 UTC, SouadHadjiat commented
**PR status** 

- waiting for more reviews and tests.
- some review comments have already been applied in latest commits. There are still a few to work on.

2023-10-12 06:49 UTC, RomuDeuxfois commented on opencti-platform/opencti-graphql/src/database/file-storage.js
> +      messages: [],
Ok, but we reverse the properties order.
Is that ok ?

2023-10-12 09:37 UTC, RomuDeuxfois approved these changes

2023-10-12 11:15 UTC, Kedae commented
We need to test perf before merging

2023-10-12 11:22 UTC, Kedae requested changes, later dismissed

2023-10-12 11:22 UTC, Kedae commented on opencti-platform/opencti-graphql/src/manager/fileIndexManager.ts
> +import { clearIntervalAsync, setIntervalAsync, type SetIntervalAsyncTimer } from 'set-interval-async/fixed';
We need to test perf before merging

2023-10-17 15:19 UTC, SouadHadjiat commented
FileIndexManager is now disabled by default in configuration (default.json), PR is ready to be merged when master is stable @Kedae @richard-julien

2023-10-23 10:10 UTC, SouadHadjiat commented
PR ready to be merged, `fileIndexManager` is now completely disabled @richard-julien @Kedae

2023-11-06 15:12 UTC, SouadHadjiat commented
**PR status**
Ready for review

2023-11-09 15:48 UTC, merged