[frontend] Fix correlated cases is not working
LuatixHQ/opencti pull request #4818
Opened 2023-10-31 09:39 UTC by Megafredo

### Proposed changes

* Updating the ternary operator in the "CaseIncidentDetail" file
* Adding the ternary operator in the "ReportDetail" file to replace empty space with '-'

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/4803

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-10-31 10:47 UTC, jpkha commented on opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentDetails.tsx
> +          {(data.relatedContainers?.edges ?? []).length >= 2
I think you can write something like this instead :
`data.relatedContainers?.edges?.length >= 2`

2023-10-31 10:49 UTC, jpkha commented on opencti-platform/opencti-front/src/private/components/analyses/reports/ReportDetails.jsx
> +          {(report.relatedContainers?.edges ?? []).length >= 2
I think you can write something like this instead :
data.relatedContainers?.edges?.length >= 2

2023-11-02 09:23 UTC, jpkha approved these changes

2023-11-02 14:54 UTC, Kedae requested changes

2023-11-02 14:54 UTC, Kedae commented on opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentDetails.tsx
> +          {(data.relatedContainers?.edges && data.relatedContainers.edges.length >= 2)
Not sure, let's talk about that

2023-11-02 14:59 UTC, Kedae commented on opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentDetails.tsx
> +          {(data.relatedContainers?.edges && data.relatedContainers.edges.length >= 2)
You need to extract the filtering of the list before the return and check that this computed list as at least one element

2023-11-05 16:14 UTC, merged