[Frontend/Backend] Quick fixes for existing CSV Mapper (#4932)
LuatixHQ/opencti pull request #5152
Opened 2023-12-08 09:41 UTC by CelineSebe

### Proposed changes

* Fix refresh validity status of required inputs when changing entity type
* Look into why there is two fields abstract in type Note
* Do not send fields authorized_members, casetemplate, authorized_authorities, grantable_groups

### Related issues

* #4932 
*

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-12-12 08:18 UTC, lndrtrbn commented
wip

2023-12-14 10:30 UTC, lndrtrbn commented
About the following issue: when changing the entity type inside a representation bloc, the errors were not reset and kept the state of the previous entity.

We need to rework a bit how errors were managed inside the form. Initially they were managed using `useState` directly in components and went through components to components using props. But it wasn't working well, so we change this to use the error system given by Formik. There is still some parts of the code that are a bit strange but we had to go for a solution in a given amount of time.

A next step would be to rework the form to create custom components for Representation blocs using the Formik API to fully integrate Formik errors system easily. Out of scope for our case right now.

2023-12-15 08:41 UTC, labo-flg requested changes
We noticed some performance issues with the changes on form validation.
Once you add a dozen representation, try to update the name or add a new representation : this can take several seconds to update.

2023-12-15 11:07 UTC, labo-flg approved these changes

2023-12-15 11:10 UTC, merged