[frontend]Quick subcription button is working properly(#5963)
LuatixHQ/opencti pull request #6002
Opened 2024-02-16 10:27 UTC by CelineSebe

### Proposed changes

* [frontend] Take out usePreloadedQuery function
* [frontend] Add useEffect to update existingInstanceTriggersEdges

### Related issues

* #5963 
*

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-02-16 10:51 UTC, frapuks approved these changes
it works

2024-02-16 14:38 UTC, Kedae requested changes
We need to check with @Archidoit what was the goal of the previous code

2024-02-16 15:01 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectQuickSubscriptionContent.tsx
> -    searchInstanceTriggers();
this was to update the instance triggers list in case the user had deleted/updated one of triggers via the quick subscription edition panel

2024-02-16 15:01 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectQuickSubscriptionContent.tsx
> -    searchInstanceTriggers();
but seems to work without it now that the 'pagination keys' are the same as Céline told me

2024-02-19 17:29 UTC, Kedae approved these changes

2024-02-19 17:32 UTC, Kedae requested changes
I read wrong Cathia message, we need to discuss it

2024-02-20 14:41 UTC, Kedae approved these changes

2024-02-20 14:43 UTC, merged