[frontend] indicator generation Text displayed false (#6845)
LuatixHQ/opencti pull request #6890
Opened 2024-05-06 10:15 UTC by ValentinBouzinFiligran

…6845)

### Proposed changes

* promote drawer on a new file
* new translation depending of type added

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/6845
*

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-05-06 15:42 UTC, SouadHadjiat requested changes
There is an issue when opening a report -> entities -> select indicators only -> click on toolbar "promote" action => nothing happens, the drawer doesn't open.

2024-05-07 16:16 UTC, SouadHadjiat commented on opencti-platform/opencti-front/src/private/components/data/drawers/PromoteDrawer.tsx
> +const PromoteDrawer = ({ isOpen, onClose, observablesFiltered, onSubmit, isIndicator }: DrawerContainerPropsType) => {
I don't really understand the parameters observablesFiltered and isIndicator. What values can they have ? Can we have observablesFiltered and isIndicator true ? so we have observables and indicators to promote at the same time ?

2024-05-13 09:25 UTC, SouadHadjiat approved these changes
tested locally

2024-05-15 07:50 UTC, lndrtrbn requested changes

2024-05-15 07:50 UTC, lndrtrbn commented on opencti-platform/opencti-front/src/private/components/data/drawers/PromoteDrawer.tsx
> +}));
`makeStyles` is deprecated, use properties `sx` and `style` directly in JSX instead

2024-05-15 07:50 UTC, lndrtrbn commented on opencti-platform/opencti-front/src/private/components/data/drawers/PromoteDrawer.tsx
> +      <>
No need for this empty fragment as there is only one child

2024-05-15 07:53 UTC, lndrtrbn commented on opencti-platform/opencti-front/src/private/components/data/drawers/PromoteDrawer.tsx
> +}));
You can have a look at `WidgetTimeline.tsx` if you need an example

2024-05-15 08:20 UTC, lndrtrbn approved these changes

2024-05-15 08:55 UTC, merged