[frontend] Fix incorrect use of stixCoreRelationshipDistribution queries (#6873)
LuatixHQ/opencti pull request #6910
Opened 2024-05-07 16:44 UTC by marieflorescontact

### Proposed changes

* use `StixRelationshipsHorizontalBars` instead of ` EntityStixCoreRelationshipsHorizontalBars`
* 

### Related issues

* [issue/6873](https://github.com/OpenCTI-Platform/opencti/issues/6873)

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

2024-05-13 07:34 UTC, labo-flg commented on opencti-platform/opencti-front/src/private/components/analyses/reports/ReportDetails.jsx
> +              parameters={'Entities distribution'}
parameters is not an object?

2024-05-13 07:40 UTC, labo-flg commented on opencti-platform/opencti-front/src/private/components/analyses/reports/ReportDetails.jsx
> +              parameters={'Entities distribution'}
judging from the use of `parameters` [here](https://github.com/OpenCTI-Platform/opencti/blob/c394cc812d99db764aba933376cd0089990eba1a/opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsHorizontalBars.jsx#L166) and [there](https://github.com/OpenCTI-Platform/opencti/blob/c394cc812d99db764aba933376cd0089990eba1a/opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsHorizontalBars.jsx#L184) you probably
want to set `parameters={{ title: 'Entities distribution' }}`

2024-05-13 07:42 UTC, labo-flg commented on opencti-platform/opencti-front/src/private/components/analyses/reports/ReportDetails.jsx
> +      },
you can `import { emptyFilterGroup } from '../../../utils/filters/filtersUtils';` to simplify this part

```suggestion
      dynamicFrom: emptyFilterGroup,
      dynamicTo: emptyFilterGroup,
```

2024-05-14 12:24 UTC, marieflorescontact commented
PR status: all comments have been taken into account

2024-05-14 12:43 UTC, labo-flg commented on opencti-platform/opencti-front/src/private/components/analyses/reports/ReportDetails.jsx
> +              withExportPopover={true}
```suggestion
```

2024-05-14 12:43 UTC, labo-flg commented on opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingDetails.jsx
> +              withExportPopover={true}
```suggestion
```

2024-05-14 12:44 UTC, labo-flg requested changes
We do not want to be able to export as image the result of this widget, if we want same behavior as before

2024-05-14 12:46 UTC, marieflorescontact commented on opencti-platform/opencti-front/src/private/components/analyses/reports/ReportDetails.jsx
> +              withExportPopover={true}
oups I forgot this

2024-05-14 15:05 UTC, labo-flg approved these changes

2024-05-14 15:08 UTC, merged