[frontend] empty array as default value added for relationship type (…
LuatixHQ/opencti pull request #6923
Opened 2024-05-10 12:25 UTC by ValentinBouzinFiligran

…#6919)

### Proposed changes

* empty array added for relationshipTypes to avoid crach on R.head(relationshipTypes)
*

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/6919
*

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

2024-05-14 07:48 UTC, marieflorescontact approved these changes

2024-05-14 15:01 UTC, Kedae requested changes

2024-05-14 15:01 UTC, Kedae commented on opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromEntity.jsx
> +    let relationshipTypes = [];
Not sure to understand the change, let's talk about it.

2024-05-16 16:51 UTC, ValentinBouzinFiligran commented on opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromEntity.jsx
> +    let relationshipTypes = [];
Just a quick fix
I talked with the product, we will create a new task 

some behaviors are broken

2024-05-17 10:00 UTC, SouadHadjiat commented on opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromEntity.jsx
> +    let relationshipTypes = [];
There was also this open bug https://github.com/OpenCTI-Platform/opencti/issues/6959 for the same issue for which I spent 1h and seeing this same issue in the code, but there are indeed other issues with this screen.

2024-05-22 09:24 UTC, ValentinBouzinFiligran commented
This PR is just to avoid the crash
Another one has been created to rework the next part : https://github.com/OpenCTI-Platform/opencti/issues/7064

2024-05-23 08:17 UTC, Kedae approved these changes

2024-05-23 08:18 UTC, merged