[frontend] Add ability to override confidence per entity type in Group (#6878)
LuatixHQ/opencti pull request #7001
Opened 2024-05-17 09:16 UTC by JeremyCloarec

### Proposed changes

*  [ ]  add Capabilities tab to group edition
*  [ ] fix behavior in user and group capabilities tab:
   *  [ ]  prevent adding multiple overrides without an entity type
   *  [ ]  prevent adding the same entity type twice
   *  [ ]  restrict entity type selection 
   *  [ ]  refactor user and group component to prevent code duplication

### Related issues

* #6878 

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

2024-05-28 08:16 UTC, lndrtrbn commented on opencti-platform/opencti-front/src/private/components/settings/users/edition/UserEditionConfidence.tsx
> +                    onClick={() => arrayHelpers.push({ entity_type: '', max_confidence: user.effective_confidence_level && user.effective_confidence_level.max_confidence ? user.effective_confidence_l
Badass cette ligne de code

Could be a function or at least separate into multiple lines?

2024-05-28 08:16 UTC, lndrtrbn commented on opencti-platform/opencti-front/src/private/components/settings/users/edition/ConfidenceOverrideField.tsx
> +  const entityTypesToOverride = availableEntityTypes.filter((entity_type) => entity_type.type !== 'entity_Stix-Meta-Objects' && entity_type.type !== 'entity_Stix-Cyber-Observables');
Badass cette ligne de code

Could be a function or at least separate into multiple lines?

2024-05-28 08:32 UTC, lndrtrbn commented
![image](https://github.com/OpenCTI-Platform/opencti/assets/33682259/38ce47f5-0e02-40a8-b8a0-181e0d92cd22)

When opening the dropdown to select an entity type to override

2024-05-28 08:34 UTC, lndrtrbn commented
![image](https://github.com/OpenCTI-Platform/opencti/assets/33682259/7575f418-6201-475c-b9f0-f63f0af8170a)

Should it be "Confiance" for French translation?

2024-05-28 08:34 UTC, SarahBocognano approved these changes
Tested ✅

2024-05-28 08:35 UTC, lndrtrbn requested changes
cf above

2024-05-28 08:38 UTC, lndrtrbn commented
App crash when cleaning the entity type field

https://github.com/OpenCTI-Platform/opencti/assets/33682259/529fa3c2-53d5-4a96-975f-d8a18fc88770

2024-05-28 08:41 UTC, lndrtrbn commented
![image](https://github.com/OpenCTI-Platform/opencti/assets/33682259/e2c28468-08cf-44f7-b8d2-e8cc86fc0bc1)

Feels odd to have "00" instead of "0"

2024-05-29 07:45 UTC, Archidoit commented
tested OK 👍

2024-05-29 07:46 UTC, Archidoit approved these changes

2024-05-29 12:08 UTC, lndrtrbn approved these changes

2024-05-29 12:20 UTC, merged