[frontend] Narratives Lines views refacto  (#6741)
LuatixHQ/opencti pull request #7608
Opened 2024-07-05 09:32 UTC by Gwendoline-FAVRE-FELIX

## Proposed changes

- Creation of two views for narratives : 

         - One with massive operations, filters and columns.
         - One with the display of sub-narratives.

## Related issues

- https://github.com/OpenCTI-Platform/opencti/issues/6741

2024-07-19 08:19 UTC, Archidoit approved these changes

2024-07-19 08:20 UTC, lndrtrbn requested changes

2024-07-19 08:20 UTC, lndrtrbn commented on opencti-platform/opencti-front/src/components/ViewSwitchingButtons.tsx
> +});
Do not use `makeStyles` which is deprecated. Put styles directly in the JSX using `style={{...}}`

2024-07-19 08:20 UTC, lndrtrbn commented on opencti-platform/opencti-front/src/components/ViewSwitchingButtons.tsx
> +    <>
You do not need this empty fragment as you have only one child below

2024-07-19 08:37 UTC, lndrtrbn commented on opencti-platform/opencti-front/src/components/ViewSwitchingButtons.tsx
> +          <Tooltip title={t_i18n('Cards view')}>
Prefer put the `Tooltip` above the `ToggleButton` otherwise only the icon will have the tooltip, the padding inside the button won't

2024-07-19 08:37 UTC, lndrtrbn commented on opencti-platform/opencti-front/src/components/ViewSwitchingButtons.tsx
> +          <Tooltip title={t_i18n('Cards view')}>
Same for other buttons

2024-07-19 08:37 UTC, lndrtrbn commented on opencti-platform/opencti-front/src/private/components/common/FiligranIcon.tsx
Why using an internal component with a `forwardRef` and then a styled component instead of a "classic" component here? It feels not so easy to read

2024-07-19 08:37 UTC, lndrtrbn commented on opencti-platform/opencti-front/src/private/components/techniques/Narratives.tsx
> +}));
Same comment about deprecated makeStyles

2024-07-19 08:37 UTC, lndrtrbn commented on opencti-platform/opencti-front/src/private/components/techniques/Narratives.tsx
Why do we are not using the new component DataTable ? I think it has been asked to use it in the Notion page of the feature

2024-07-19 08:37 UTC, lndrtrbn commented on opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeLine.tsx
> +}));
Deprecated 😁

2024-07-19 08:37 UTC, lndrtrbn commented on opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeWithSubnarrativeLine.tsx
> +}));
Deprecated 😁

2024-07-19 08:37 UTC, lndrtrbn commented on opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativesWithSubnarrativesLines.tsx
> +}));
Deprecated 😁

2024-07-19 12:12 UTC, lndrtrbn commented on opencti-platform/opencti-front/src/private/components/techniques/Narratives.tsx
Will be done later

2024-07-23 09:41 UTC, lndrtrbn approved these changes

2024-07-23 11:53 UTC, merged