[frontend] fix attack patterns details with not "empty" signs "-" (#7869)
LuatixHQ/opencti pull request #7909
Opened 2024-08-01 07:53 UTC by CelineSebe

…869)

### Proposed changes

* add ternary 

### Related issues

* #7869 
*

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

2024-08-01 09:10 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternCoursesOfAction.jsx
> +          : ('-')
use the FieldOrEmpty component instead of a ternary

2024-08-01 09:10 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDataComponents.tsx
> +        : ('-')
same

2024-08-01 09:10 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx
> +                    {propOr([], 'x_mitre_platforms', attackPattern).map(
```suggestion
                    {(attackPattern?.x_mitre_platforms ?? []).map(
```

2024-08-01 09:10 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx
> +                  : ('-')
same

2024-08-01 09:12 UTC, Archidoit commented
Too much space before the '-' for Course of Action, Data Components, and Sub attack patterns  (compare with space before '-' of Platforms for instance):
![image](https://github.com/user-attachments/assets/03d641d0-9696-4ff0-9b90-e6f92d44cb48)

2024-08-01 09:13 UTC, Archidoit commented
If empty, external ID should be '-', not a blue space 

![image](https://github.com/user-attachments/assets/8e528bd0-9b91-4ab4-9e6b-a20e0f430938)

2024-08-01 09:14 UTC, Archidoit requested changes

2024-08-01 09:14 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx
> +                : ('-')
same

2024-08-02 08:49 UTC, CelineSebe commented
@Archidoit Every change has been addressed

2024-08-02 09:19 UTC, Archidoit requested changes

2024-08-02 09:19 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx
> +                  <FieldOrEmpty source={attackPattern.attackPattern}>
```suggestion
                  <FieldOrEmpty source={attackPattern.x_mitre_platforms}>
```

2024-08-02 09:19 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx
> +                    {(attackPattern?.x_mitre_platforms || []).map(
```suggestion
                    {attackPattern.x_mitre_platforms.map(
```

2024-08-02 09:19 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx
> +                <FieldOrEmpty source={attackPattern.attackPattern}>
```suggestion
                <FieldOrEmpty source={attackPattern.x_mitre_permissions_required}>
```

2024-08-02 09:19 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx
> +                  {propOr([], 'x_mitre_permissions_required', attackPattern).map(
remove ramda

2024-08-02 09:34 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx
> +                    {(attackPattern.x_mitre_platforms).map(
```suggestion
                    {attackPattern.x_mitre_platforms?.map(
```

2024-08-02 10:04 UTC, Archidoit approved these changes

2024-08-02 12:25 UTC, merged