Required fields techniques
LuatixHQ/opencti pull request #9113
Opened 2024-11-21 16:28 UTC by daimyo007

### Proposed changes

This PR builds upon the capabilities from https://github.com/OpenCTI-Platform/opencti/pull/6972. This PR will add all capabilities from the previous PR to the 'Techniques' section of the platform, to include creating and editing the following entity types:

* Attack patterns
* Narratives
* Courses of action
* Data components
* Data sources

### Related issues
* As stated in https://github.com/OpenCTI-Platform/opencti/pull/6972, the External-Reference field is not directly supported for this required fields change. Based on communication with the Filigran team - this field will require many complex relationships between mandatory attributes to fully implement.

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] (N/A - Existing test cases should work properly) I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### Further comments

* In Course of Action the fields 'x_mitre_id', 'x_opencti_threat_hunting', and 'x_opencti_log_sources' are only present on the Edit form and not the Create form or the Customization fields.
* The 'KillChainPhase' field is not showing a '*' even though it is required and turns red on submit. May be an issue with the field itself.

2025-01-29 19:19 UTC, ParamConstructor commented on opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/CourseOfActionEditionOverview.jsx
> -      'x_mitre_id',
Removed because in array already about six lines up (i.e. in array (2) times on accident)

2025-01-29 20:05 UTC, ParamConstructor commented
Attack patterns
  - [X] Create
       - [X] Name (Note - Not Configurable, always required)
       - [X] External Id
       - [X] Description
       - [X] Confidence (Note - Not Configurable, mandatory always off, but no way not to submit it on form)
       - [X] Kill Chain Phases
       - [X] Author
       - 🚫 Labels (Note - Not in Customize Settings)
       - [X] Marking
       - 🚫 External Ref (Skipped - Controlled Externally)
       - 🚫 File - Skipped Controlled Externally)
  - [X] Update (Note - Labels is NOT on Update Form)
       - [X] Name (Note - Not Configurable, always required)
       - [X] External Id
       - [X] Description
       - [X] Confidence (Note - Not Configurable, mandatory always off, but no way not to submit it on form)
       - [X] Kill Chain Phases
       - [X] Author
       - [X] Marking
       - 🚫 Platforms (Note - Not Configurable, Not on Create Form)
       - 🚫 Required Permissions (Note - Not Configurable, Not on Create Form)
       - 🚫 Detection (Note - Not Configurable, Not on Create Form)
 
Narratives
  - [X] Create
       - [X] Name (Note - Not Configurable, always required)
       - [X] Description
       - [X] Confidence (Note - Not Configurable, mandatory always off, but no way not to submit it on form)
       - [X] Author
       - 🚫 Labels (Note - Not in Customize Settings)
       - [X] Marking
       - 🚫 External Ref (Skipped - Controlled Externally)
       - 🚫 File - Skipped Controlled Externally)
  - [X] Update (Note - Labels is NOT on Update Form)
       - [X] Name (Note - Not Configurable, always required)
       - [X] Description
       - [X] Confidence (Note - Not Configurable, mandatory always off, but no way not to submit it on form)
       - [X] Author
       - [X] Marking
   
Courses of action
  - [X] Create
       - [X] Name (Note - Not Configurable, always required)
       - [X] Description
       - [X] Confidence (Note - Not Configurable, mandatory always off, but no way not to submit it on form)
       - [X] Author
       - 🚫 Labels (Note - Not in Customize Settings)
       - [X] Marking
       - 🚫 External Ref (Skipped - Controlled Externally)
       - 🚫 File - Skipped Controlled Externally)
  - [X] Update (Note - Labels is NOT on Update Form)
       - [X] Name (Note - Not Configurable, always required)
       - 🚫 External Id (Note - Not Configurable, Not on Create Form)
       - [X] Description
       - [X] Confidence (Note - Not Configurable, mandatory always off, but no way not to submit it on form)
       - [X] Author
       - [X] Marking

Data components
  - Create and Create Multiple
       - [X] Name (Note - Not Configurable, always required)
       - [X] Description
       - [X] Confidence (Note - Not Configurable, mandatory always off, but no way not to submit it on form)
       - [X] Author
       - 🚫 Labels (Note - Not in Customize Settings)
       - [X] Marking
       - 🚫 External Ref (Skipped - Controlled Externally)
       - 🚫 File - Skipped Controlled Externally)
  - Update (Note - Labels is NOT on Update Form)
       - [X] Name (Note - Not Configurable, always required)
       - [X] Description
       - [X] Confidence (Note - Not Configurable, mandatory always off, but no way not to submit it on form)
       - [X] Author
       - [X] Marking
  
Data sources
  - [X] Create and Create Multiple
       - [X] Name (Note - Not Configurable, always required)
       - [X] Description
       - [X] Confidence (Note - Not Configurable, mandatory always off, but no way not to submit it on form)
       - [X] Author
       - 🚫 Labels (Note - Not in Customize Settings)
       - [X] Marking
       - [X] Platforms
       - [X] Layers
       - 🚫 External Ref (Skipped - Controlled Externally)
       - 🚫 File - Skipped Controlled Externally)
  - [X] Update (Note - Labels is NOT on Update Form)
       - [X] Name (Note - Not Configurable, always required)
       - [X] Description
       - [X] Confidence (Note - Not Configurable, mandatory always off, but no way not to submit it on form)
       - [X] Author
       - [X] Marking
       - [X] Platforms
       - [X] Layers


Fields not in Customize settings, thus not tested:
  Attack Pattern
      - 🚫 Labels
      - 🚫 Platforms (Note - Not on Create Form)
      - 🚫 Required Permissions (Note - Not on Create Form)
      - 🚫 Detection (Note - Not on Create Form)
   
  Narratives
      - 🚫 Labels
    
  Course of Action
      - 🚫 Labels
      - 🚫 External ID (Note: Not on Create Form)
      - 🚫 Threat Hunting Techniques (Note: Not on Create Form)
      - 🚫 Log Sources (Note: Not on Create Form)
  
  Data Components
      - 🚫 Labels
   
  Data Sources
      - 🚫 Labels

2025-03-17 10:13 UTC, frapuks commented
- [x]  Attack Pattern
    - [x]  Create
    - [x]  Update
- [x]  Narratives
    - [x]  Create
    - [x]  Update
- [x]  Courses of action
    - [x]  Create
    - [x]  Update
- [x]  Data components
    - [x]  Create
    - [x]  Update
- [x]  Data sources
    - [x]  Create
    - [x]  Update

2025-03-17 10:26 UTC, frapuks requested changes

2025-03-17 10:26 UTC, frapuks commented on opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/CourseOfActionCreation.tsx
> +        <Form style={{ margin: '20px 0 20px 0' }}>
Please remove this margin
```suggestion
        <Form>
```

2025-03-17 10:26 UTC, frapuks commented on opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/CourseOfActionEditionOverview.jsx
> -      'x_mitre_id',
ok

2025-03-17 10:26 UTC, frapuks commented on opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/CourseOfActionEditionOverview.jsx
> +        <Form style={{ margin: '20px 0 20px 0' }}>
```suggestion
        <Form>
```

2025-03-17 10:26 UTC, frapuks commented on opencti-platform/opencti-front/src/private/components/techniques/data_components/DataComponentCreation.tsx
> +          <Form style={{ margin: '20px 0 20px 0' }}>
```suggestion
          <Form>
```

2025-03-17 10:26 UTC, frapuks commented on opencti-platform/opencti-front/src/private/components/techniques/data_components/DataComponentEditionOverview.tsx
> +        <Form style={{ margin: '20px 0 20px 0' }}>
```suggestion
        <Form>
```

2025-03-17 10:26 UTC, frapuks commented on opencti-platform/opencti-front/src/private/components/techniques/data_sources/DataSourceCreation.tsx
> +          <Form style={{ margin: '20px 0 20px 0' }}>
```suggestion
          <Form>
```

2025-03-17 10:26 UTC, frapuks commented on opencti-platform/opencti-front/src/private/components/techniques/data_sources/DataSourceEditionOverview.tsx
> +        <Form style={{ margin: '20px 0 20px 0' }}>
```suggestion
        <Form>
```

2025-03-17 10:26 UTC, frapuks commented on opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeCreation.tsx
> +          <Form style={{ margin: '20px 0 20px 0' }}>
```suggestion
          <Form>
```

2025-03-17 10:26 UTC, frapuks commented on opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeEditionOverview.jsx
> +        <Form style={{ margin: '20px 0 20px 0' }}>
```suggestion
        <Form>
```

2025-03-17 14:05 UTC, ParamConstructor commented on opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/CourseOfActionCreation.tsx
> +        <Form style={{ margin: '20px 0 20px 0' }}>
@frapuks - Corrected

2025-03-17 14:05 UTC, ParamConstructor commented on opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/CourseOfActionEditionOverview.jsx
> +        <Form style={{ margin: '20px 0 20px 0' }}>
@frapuks - Corrected

2025-03-17 14:05 UTC, ParamConstructor commented on opencti-platform/opencti-front/src/private/components/techniques/data_components/DataComponentCreation.tsx
> +          <Form style={{ margin: '20px 0 20px 0' }}>
@frapuks - Corrected

2025-03-17 14:05 UTC, ParamConstructor commented on opencti-platform/opencti-front/src/private/components/techniques/data_components/DataComponentEditionOverview.tsx
> +        <Form style={{ margin: '20px 0 20px 0' }}>
@frapuks - Corrected

2025-03-17 14:05 UTC, ParamConstructor commented on opencti-platform/opencti-front/src/private/components/techniques/data_sources/DataSourceCreation.tsx
> +          <Form style={{ margin: '20px 0 20px 0' }}>
@frapuks - Corrected

2025-03-17 14:06 UTC, ParamConstructor commented on opencti-platform/opencti-front/src/private/components/techniques/data_sources/DataSourceEditionOverview.tsx
> +        <Form style={{ margin: '20px 0 20px 0' }}>
@frapuks - Corrected

2025-03-17 14:06 UTC, ParamConstructor commented on opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeCreation.tsx
> +          <Form style={{ margin: '20px 0 20px 0' }}>
@frapuks - Corrected

2025-03-17 14:06 UTC, ParamConstructor commented on opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeEditionOverview.jsx
> +        <Form style={{ margin: '20px 0 20px 0' }}>
@frapuks - Corrected

2025-03-19 13:41 UTC, frapuks approved these changes

2025-03-19 13:41 UTC, merged