[frontend] clamp confidence input values between 0 and 100 (#6715)
LuatixHQ/opencti pull request #9119
Opened 2024-11-22 13:58 UTC by delemaf

### Proposed changes

* clamp confidence input field values between 0 and 100 🗜️ 

### Related issues

* Close [When an indicator score is set to 1000000, the object does not load properly and the system hangs](https://github.com/OpenCTI-Platform/opencti/issues/6715)
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### Further comments

2024-11-25 09:36 UTC, lndrtrbn requested changes
From live discussions :
- rename component `InputScaleField`
- remove the bloc `if(variant === edit) {...}` and adapt the one we kept
- use min max attributes from input field number instead of a callback on change

2024-11-27 15:28 UTC, SouadHadjiat commented
The issue https://github.com/OpenCTI-Platform/opencti/issues/6715 is about indicator score, not confidence, why is this PR about confidence ?

2024-11-27 16:18 UTC, delemaf commented
> The issue #6715 is about indicator score, not confidence, why is this PR about confidence ?

I think I may have confused the score with the confidence, I'll move what I've done for confidence in score

2025-03-25 07:38 UTC, delemaf commented
PR have been reworked to handle min and max in front and back.

2025-03-26 08:49 UTC, lndrtrbn reviewed
Could we add a test in backend to try creating + editing an indicator with score > 100 ?

2025-04-09 13:38 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorCreation.tsx
> +      .min(0, t_i18n('The value must be greater than or equal to 0'))
maybe indicate directly the range? 'value between 0 and 100' ? (only a suggestion)

2025-04-09 13:42 UTC, delemaf commented on opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorCreation.tsx
> +      .min(0, t_i18n('The value must be greater than or equal to 0'))
We already have theses translations and kind of validation on other data (ex: confidence) so I didn't wanted to introduce new wording :wink:

2025-04-09 13:42 UTC, Archidoit commented
When I update an indicator with a score out of 0-100, the query is sent to the backend, resulting in an error message ('The score should be between 0 and 100)
![image](https://github.com/user-attachments/assets/68b6297f-26a8-4880-a607-f18585c637b6)


--> it'not the case for other fields (if the field is not validated, it is not sent to the backend)
Example: enter an invalid start date, you get no messaging error at the top (only the validator error message), the invalid start date is not sent to the backend

2025-04-09 13:43 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorCreation.tsx
> +      .min(0, t_i18n('The value must be greater than or equal to 0'))
I understand, perfect :)

2025-04-09 13:58 UTC, Archidoit approved these changes

2025-04-09 13:58 UTC, Archidoit commented
> When I update an indicator with a score out of 0-100, the query is sent to the backend, resulting in an error message ('The score should be between 0 and 100) ![image](https://private-user-images.githubusercontent.com/75783086/431868839-68b6297f-26a8-4880-a607-f18585c637b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQyMDczODcsIm5iZiI6MTc0NDIwNzA4NywicGF0aCI6Ii83NTc4MzA4Ni80MzE4Njg4MzktNjhiNjI5N2YtMjZhOC00ODgwLWE2MDctZjE4NTg1YzYzN2I2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDA5VDEzNTgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNWUxZDlhYTczODU3MTBhNzc2NjM0MTIwMzBmMDY3NGMzMmE4ZDk0ZjlkMjY5MGFjZTI5MjRlNDFkOTY1ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mHViaWJxtxUh6wMgjx2DznUXbxHNPNkkvPQSdXXKTjo)
> 
> --> it'not the case for other fields (if the field is not validated, it is not sent to the backend) Example: enter an invalid start date, you get no messaging error at the top (only the validator error message), the invalid start date is not sent to the backend

will be fixed in https://github.com/OpenCTI-Platform/opencti/pull/10501

2025-04-09 14:27 UTC, lndrtrbn commented on opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableEditionOverview.jsx
> +      .max(100, 'Score must be between 0 and 100')
This is not translated

2025-04-09 14:27 UTC, lndrtrbn commented on opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/indicator-test.ts
> +  it('should not update indicator with score value outside of 0 and 100', async () => {
Rename to explain the test: negative value

2025-04-09 14:27 UTC, lndrtrbn commented on opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/indicator-test.ts
> +  it('should not create indicator with score value outside of 0 and 100', async () => {
Rename to explain the test: higher than 100

2025-04-09 14:46 UTC, lndrtrbn approved these changes

2025-04-10 06:55 UTC, merged