[frontend] Show all types of containers in overview correlation widget & CTA to correlation graph (#3227)
LuatixHQ/opencti pull request #9175
Opened 2024-11-28 13:49 UTC by delemaf

### Proposed changes

* Show all types of containers in overview correlation widget
* Button CTA to correlation graph

### Related issues

* [Related containers / correlation enhancements #3227](https://github.com/OpenCTI-Platform/opencti/issues/3227)

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

2024-12-12 14:47 UTC, CelineSebe commented
Tested locally, it works 👌 

I wonder if we need to add a sentence, such as: 'No correlated containers have been found,' or a hyphen when it's empty. @nino-filigran ? 
![No correlated containers has been found](https://github.com/user-attachments/assets/47b0cdaa-68b5-468b-8c28-0a2f32648366)

I will see less padding at the bottom of this block:
![padding correlated containers](https://github.com/user-attachments/assets/3dce394d-a64f-4b97-9ffe-7023ef8d14d2)

2024-12-13 09:16 UTC, lndrtrbn commented on opencti-platform/opencti-front/src/private/components/common/containers/RelatedContainers.tsx
> +        <IconButton
Could be nice to add a tooltip around the button here, also maybe reuse the same icon used in Knowledge tab for the correlation view button. The icon used here I thought I would go outside the app.

2024-12-13 09:16 UTC, lndrtrbn commented on opencti-platform/opencti-front/src/private/components/common/containers/RelatedContainers.tsx
> +          style={{ marginBottom: 4 }}
When you play with spacing, think about use `theme` instead of hardcoded values. For example here for 4 you could do `theme.spacing(0.5)` (spacings are multipliers of 8)

2024-12-13 09:16 UTC, lndrtrbn commented on opencti-platform/opencti-front/src/private/components/common/containers/RelatedContainers.tsx
Nice move for the new component 👍

2024-12-13 09:16 UTC, lndrtrbn commented on opencti-platform/opencti-front/src/private/components/common/containers/RelatedContainers.tsx
> +        <IconButton
Also change the button to a link so we can open in new tab etc

2024-12-13 09:16 UTC, lndrtrbn commented on opencti-platform/opencti-front/src/private/components/common/containers/RelatedContainers.tsx
> +        <IconButton
@nino-filigran

2024-12-13 14:18 UTC, delemaf commented on opencti-platform/opencti-front/src/private/components/common/containers/RelatedContainers.tsx
> +        <IconButton
Approved by Nino 👍

2024-12-13 16:16 UTC, CelineSebe requested changes

2024-12-13 16:16 UTC, CelineSebe commented on opencti-platform/opencti-front/src/private/components/common/containers/RelatedContainers.tsx
> +      <Typography variant="h3" gutterBottom={true} style={{ }}>
```suggestion
      <Typography variant="h3" gutterBottom={true}>
```

2024-12-13 16:30 UTC, CelineSebe approved these changes

2024-12-16 10:27 UTC, lndrtrbn approved these changes

2024-12-16 10:28 UTC, merged