[backend] List all restricted Stix Core Objects
LuatixHQ/opencti pull request #9219
Opened 2024-12-03 14:20 UTC by marieflorescontact

### Proposed changes

*
*

### Related issues

*
*

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

2024-12-13 10:43 UTC, delemaf reviewed
Tested functionally 🚀 Just few little code suggestion

2024-12-13 10:43 UTC, delemaf commented on opencti-platform/opencti-front/src/components/dataGrid/DataTable.tsx
> +            {('This list displays all the entities that have some access restriction enabled, meaning that they are only accessible to some specific users. You can remove this access restriction on t
Looks like i18n is missing.
```suggestion
            {t_i18n('This list displays all the entities that have some access restriction enabled, meaning that they are only accessible to some specific users. You can remove this access restriction on this screen.')}
```

2024-12-13 10:43 UTC, delemaf commented on opencti-platform/opencti-front/src/private/components/data/Management.tsx
> +  const isRuntimeSort = isRuntimeFieldEnable() ?? false;
`isRuntimeFieldEnable` seems to always return a **bool** nullish coalescing operator might be useless.
```suggestion
  const isRuntimeSort = isRuntimeFieldEnable();
```

2024-12-13 13:15 UTC, aHenryJard commented on opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
> +export const findAllRestricted = async (context, user, args) => {
Would be better to add detail on restricted, because some entity can be restricted because of marking or organization. Feel free to use another name than my proposal.
```suggestion
export const findAllAuthMemberRestricted = async (context, user, args) => {
```

2024-12-13 13:17 UTC, aHenryJard commented on opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/container-authorized-members-test.ts
> +  it('should not list all restricted entities', async () => {
```suggestion
  it('user without bypass should not be allowed list all auth member restricted entities', async () => {
```

2024-12-13 13:18 UTC, aHenryJard commented on opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/container-authorized-members-test.ts
> +  it('should BYPASS user list all restricted entities', async () => {
```suggestion
  it('should BYPASS user be allowed list all auth member restricted entities', async () => {
```

2024-12-13 13:18 UTC, aHenryJard commented on opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/container-authorized-members-test.ts
> +  it('should plateform organization sharing and EE activated', async () => {
```suggestion
  it('should platform organization sharing and EE activated', async () => {
```

2024-12-13 13:20 UTC, aHenryJard commented on opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/container-authorized-members-test.ts
> +  it('should not list all restricted entities', async () => {
```suggestion
  it('using platform org - user without bypass should not be allowed list all auth member restricted entities', async () => {
```

2024-12-13 13:21 UTC, aHenryJard commented on opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/container-authorized-members-test.ts
> +  it('should BYPASS user list all restricted entities', async () => {
```suggestion
  it('should BYPASS user be allowed list all auth member restricted entities', async () => {
```

2024-12-13 13:22 UTC, aHenryJard commented on opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/container-authorized-members-test.ts
> +  it('should plateform organization sharing and EE deactivated', async () => {
```suggestion
  it('should platform organization sharing and EE deactivated', async () => {
```

2024-12-13 13:26 UTC, aHenryJard requested changes
The data management menu on the left is displayed without feature flag, so I'm blocking for now.

2024-12-16 13:44 UTC, CelineSebe commented
All comments are resolved. Waiting for approval.

2024-12-16 14:59 UTC, SouadHadjiat commented on opencti-platform/opencti-front/src/private/components/data/Root.jsx
> +  const isRightMenuManagementEnable = isFeatureEnable('NEW_MANAGEMENT_RIGHT_MENU');
DATA_MANAGEMENT_RIGHT_MENU

2024-12-16 14:59 UTC, SouadHadjiat commented on opencti-platform/opencti-front/src/private/components/data/Management.tsx
> +  const isRightMenuManagementEnable = isFeatureEnable('NEW_MANAGEMENT_RIGHT_MENU');
DATA_MANAGEMENT_RIGHT_MENU

2024-12-16 14:59 UTC, SouadHadjiat approved these changes

2024-12-17 09:07 UTC, aHenryJard approved these changes
Removing the change request

2024-12-17 09:10 UTC, merged