[frontend/backend] wip
LuatixHQ/opencti pull request #9250
Opened 2024-12-05 16:40 UTC by savacano28

### Proposed changes

*
*

### Related issues

*
*

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

2024-12-11 09:20 UTC, Archidoit requested changes

2024-12-11 09:20 UTC, Archidoit commented on opencti-platform/opencti-graphql/src/modules/xtm/xtm-domain.js
> +        let finalObasInjectorContracts = R.take(5, getShuffledArr(obasInjectorContracts));
try not tu use Ramda when it's possible
R.take(number, array) —> array.slice(0, number)

2024-12-11 09:20 UTC, Archidoit commented on opencti-platform/opencti-graphql/src/modules/xtm/xtm-domain.js
> +        // TODO MIXED Case
todo?

2024-12-11 09:20 UTC, Archidoit commented on opencti-platform/opencti-graphql/src/modules/xtm/xtm.graphql
> +input SimulationConfig {
in SimulationConfig there are no mandatory fields?

2024-12-11 09:20 UTC, Archidoit commented on opencti-platform/opencti-graphql/src/modules/xtm/xtm.graphql
> +type GenerationResponse {
same in GenerationResponse?

2024-12-11 09:20 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectSimulationResult.jsx
> +const stixCoreObjectSimulationResultAttackPatternForContainersQuery = graphql`
```suggestion
const stixCoreObjectSimulationResultAttackPatternsForContainersQuery = graphql`
```

2024-12-11 09:20 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectSimulationResult.jsx
> +  query StixCoreObjectSimulationResultAttackPatternForContainersQuery($id: String!) {
```suggestion
  query StixCoreObjectSimulationResultAttackPatternsForContainersQuery($id: String!) {
```

2024-12-11 09:20 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectSimulationResult.jsx
> +  query StixCoreObjectSimulationResultAttackPatternForThreatsQuery($id: Any!) {
```suggestion
  query StixCoreObjectSimulationResultAttackPatternsForThreatsQuery($id: Any!) {
```

2024-12-11 09:20 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectSimulationResult.jsx
> +                    helperText={platforms.length === 0 ? t_i18n('This field should not be empty.') : ''}
In a form, to check if the entered data are correct, we use a 'validator'. For instance, see feedCreationValidation in FeedCreation

2024-12-11 09:20 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectSimulationResult.jsx
> +const platformOptions = [
this constant is not used elsewhere, you should define it inside the function component

2024-12-12 16:24 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectSimulationResult.jsx
> +    throw new Error('Type should be container or threat');
```suggestion
    throw new Error('Type of the simulation should be container or threat');
```

2024-12-12 16:24 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectSimulationResult.jsx
> +      setPlatformError(t_i18n('This field should not be empty'));
not the way we handle error, may be harmonized

2024-12-12 16:24 UTC, Archidoit commented on opencti-platform/opencti-graphql/src/database/xtm-obas.ts
> +    const importFilter: any = {
we only use importFiler.filters, so the 'mode' part is useless

2024-12-12 16:24 UTC, Archidoit commented on opencti-platform/opencti-graphql/src/database/xtm-obas.ts
> +      filterGroup: {
we don't use filters like that in OpenCTI.. is this really working?

2024-12-17 15:12 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectSimulationResult.jsx
> +      setPlatformError(t_i18n('This field should not be empty'));
we don't do this way to set errors in form.. we should harmonize, maybe not use FormControl to be able to use our classical validators. What do you think @aHenryJard ?

2025-01-03 08:32 UTC, RomuDeuxfois commented
A new release has been done on OpenSide with the first step of this feature.
https://github.com/OpenBAS-Platform/openbas/releases/tag/1.10.1

So this PR can be merge when it's ready.

2025-01-15 07:48 UTC, aHenryJard commented on opencti-platform/opencti-graphql/src/modules/xtm/xtm-domain.js
> +    'd02e9132-b9d0-4daa-b3b1-4b9871f8472c',
Could you please use a constant for this magic ID

2025-01-15 07:55 UTC, aHenryJard commented on opencti-platform/opencti-graphql/src/modules/xtm/xtm.graphql
> +    obasVictimGenerateScenario(id: ID!, simulationConfig: SimulationConfig, filters: FilterGroup): GenerationResponse @auth(for: [KNOWLEDGE_KNUPDATE])
We do no do API breaking change, you need to create new API with new parameters (either a new name of obasContainerGenerateScenariov2)

And add @deprecated annotation in "old" methods.

2025-01-15 08:33 UTC, aHenryJard reviewed
When OBAS has error the success message is displayed in UI ("Le scénario a été correctement généré dans votre plateforme OpenBAS.") would be better to say that something has not worked IMO. Maybe better to throw exception.

2025-01-20 15:06 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectSimulationResult.jsx
> +  const attackPatterns = useLazyLoadQuery(attackPatternsQuery, { id });
We recomand to use useQueryLoading instead of useLazyLoadQuery... Do you think we can keep lazy load heare @aHenryJard ?

2025-01-21 08:13 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectSimulationResult.jsx
> +  const attackPatterns = useLazyLoadQuery(attackPatternsQuery, { id });
I'm gonna replace it myself @savacano28

2025-01-21 08:40 UTC, Archidoit commented
I pushed the modifications to remove the useLazyLoadQuery

2025-01-21 08:41 UTC, Archidoit commented
Maybe see if we can activate EE from there 
![image](https://github.com/user-attachments/assets/5026d048-e462-44be-8b9e-c2d8ce743f36)

(here chips are disabled)

2025-01-21 08:59 UTC, Archidoit commented
I do a simulation of type 'simulated emails' on a report that contains 1 attack pattern.
![image](https://github.com/user-attachments/assets/cf5af274-eae1-4743-8b77-9d9058d46966)

I have a message of success.
![image](https://github.com/user-attachments/assets/6f720ec3-785a-4690-8373-5c05d7b6ead9)


But when I click on Access scenaio, there is nothing in 'injects' : 
![image](https://github.com/user-attachments/assets/55d1b9d9-4a91-42c2-919c-46c98c1f3d84)

2025-01-21 16:08 UTC, Archidoit submitted a review, later dismissed

2025-01-22 09:28 UTC, Archidoit approved these changes

2025-01-22 09:29 UTC, merged