[frontend] In Observable / Indicators composed with this observable view the '+' button is too on the left and long description/name are troncated far before the end of the screen(#9279)
LuatixHQ/opencti pull request #9391
Opened 2024-12-17 15:12 UTC by Gwendoline-FAVRE-FELIX

### Proposed changes

* Correct the position of the + button and the width of the drawer

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/9279

2024-12-18 14:23 UTC, Archidoit submitted a review, later dismissed

2024-12-18 14:23 UTC, Archidoit commented on opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableAddIndicators.jsx
> -    width: '50%',
the opened tab should be half the screen width, why did you remove this?

2024-12-18 14:24 UTC, Archidoit commented
the opened panel is less large than other panels (it should be half the screen width)

the panel you modified:
![image](https://github.com/user-attachments/assets/8690294e-ee0d-46aa-94f6-7777146b52ab)


other panels: 
![image](https://github.com/user-attachments/assets/9ae01bed-e14c-4653-864b-546998760f4a)

![image](https://github.com/user-attachments/assets/1c221b31-8f4b-4ae2-bacb-f8fa4164e356)

2025-01-27 09:54 UTC, delemaf requested changes

2025-01-27 09:54 UTC, delemaf commented on opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntityList.js
> +                        }
The name and description are still overflowing:
![image](https://github.com/user-attachments/assets/60cba28a-97be-4a7f-a372-918f4c7a7135)

You can do this with CSS easily 😃 
```suggestion
                        secondary={defaultDescription(node)}
                        sx={{
                          '.MuiListItemText-primary, .MuiListItemText-secondary': {
                            overflowX: 'hidden',
                            textOverflow: 'ellipsis',
                            whiteSpace: 'nowrap',
                            marginRight: '20px',
                          },
                        }}
```
![image](https://github.com/user-attachments/assets/51791d82-2178-413f-9f71-03634a61cddc)

2025-01-27 09:54 UTC, delemaf commented on opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntityList.js
> +    130,
truncate could be removed if you handle this via CSS

2025-01-28 10:18 UTC, delemaf approved these changes

2025-01-28 10:19 UTC, delemaf commented on opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableAddIndicators.jsx
> -    width: '50%',
It's done 👍

2025-01-28 10:22 UTC, merged